#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################

secrets:
  aws2prem:
    file: /run/secrets/etc/nginx/conf.d/aws2prem.conf
services:
  aws2prem:
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 6
      restart_policy:
        condition: any
    image: "secobau/proxy2aws:release-5.0"
    ports:
    - "30002:80"
    secrets:
    - mode: 0440
      source: aws2prem
      target: etc/nginx/conf.d/aws2prem.conf
    volumes:
    - aws2prem:/var/log/nginx
version: '3.8'
volumes:
  aws2prem:
