#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy2aws
spec:
  replicas: 1
  selector:
    matchLabels:
      service: proxy2aws
  template:
    metadata:
      labels:
        service: proxy2aws
    spec:
      containers:
      -
        name: proxy2aws
        image: secobau/nginx:5.2@sha256:31237e77f431d0ecd42c35935b84be219f5c0b09f715c461338c5af57da82286
        volumeMounts:
        -
          name: proxy2aws-conf
          mountPath: /etc/nginx/conf.d
          readOnly: true
        -
          name: proxy2aws-logs
          mountPath: /var/log/nginx/
      volumes:
      -
        name: proxy2aws-conf
        projected:
          sources:
          - secret:
              name: aws2cloud.htpasswd
              items:
                key: aws2cloud.htpasswd
                mode: 0440
                path: aws2cloud.htpasswd
          - secret:
              name: proxy2aws.conf
              items:
                key: proxy2aws.conf
                mode: 0440
                path: proxy2aws.conf
      -
        name: proxy2aws-logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: proxy2aws
spec:
  ports:
  - port: 8080
    nodePort: 30001
  selector:
    service: proxy2aws
  type: NodePort
---
###############################################################################
# f=nginx.conf && kubectl create configmap $f --from-file $f                  ;
# f=aws2cloud.htpasswd && kubectl create secret generic $f --from-file $f     ;
# f=proxy2aws.conf && kubectl create secret generic $f --from-file $f         ;
# kubectl apply -f kube-compose.yaml                                          ;
###############################################################################
