#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################

secrets:
  aws2prem:
    file: /run/secrets/etc/nginx/conf.d/aws2prem.conf
services:
  aws2prem:
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 6
      restart_policy:
        condition: any
    image: secobau/nginx:${tag:-1.2@sha256:7ac760edcb2a0e4d9d9284dc845afb9b4786207b7677b3e55e8df00f49f84ec3}
    ports:
    - "30002:80"
    secrets:
    - mode: 0440
      source: aws2prem
      target: etc/nginx/conf.d/aws2prem.conf
    volumes:
    - aws2prem:/var/log/nginx
version: '3.8'
volumes:
  aws2prem:
