#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################

secrets:
  aws2cloud.htpasswd:
    file: /run/secrets/proxy2aws/etc/nginx/conf.d/aws2cloud.htpasswd
  proxy2aws.conf:
    file: /run/secrets/proxy2aws/etc/nginx/conf.d/proxy2aws.conf
services:
  proxy2aws:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
        - node.role == worker
    image: secobau/nginx:5.2@sha256:31237e77f431d0ecd42c35935b84be219f5c0b09f715c461338c5af57da82286
    ports:
    - "30001:8080"
    secrets:
    -
      gid: '101'
      mode: 0440
      source: aws2cloud.htpasswd
      target: /etc/nginx/conf.d/aws2cloud.htpasswd
      uid: '101'
    -
      gid: '101'
      mode: 0440
      source: proxy2aws.conf
      target: /etc/nginx/conf.d/proxy2aws.conf
      uid: '101'
    volumes:
    - proxy2aws:/var/log/nginx
version: '3.8'
volumes:
  proxy2aws:
